### ISSUE TITLE
Original value when using Iterators

### ISSUE THREAD

**Issue by dodomorandi** [NattapongSiri/permutator#11]
I am unsure if the current behaviour is intended or not. In any case, `HeapPermutationIterator` does not gives back the initial data not permutated. This is a bit unfortunate because the data is taken by mut ref, and for this reason it is impossible to use something like `std::iter::once(data).chain(HeapPermutationIterator(data))`.

Is the current behaviour something intended (and I need a different approach) or it is something that should be addressed?

**Comment by NattapongSiri** [comment]
I'm sorry for late delay.. I'm not sure why there's no email to notify me on the issue.
Anyway, my answer is yes. It's designed that way because it permute data in place so I assume that user shall already have that non-permuted data.

What do you want to achieve with it ? I'll see if I can help.

**Comment by dodomorandi** [comment]
Thank for your reply, the email issue is pretty strange indeed.

Nevertheless, I will try to show you the approach in C++, in order to make my intents clearer.
```cpp
#include <algorithm>
#include <array>
#include <cassert>
#include <numeric>

int main() {
  // Let's create an array of 5 ints
  std::array<int, 5> indices;
  // ...and fill it with numbers from 0 to 4 included
  std::iota(std::begin(indices), std::end(indices), 0);

  // Let's count the number of times we are evaluating indices
  std::size_t n_evaluations = 0;
  do {
    // We increment the number of evaluations
    ++n_evaluations;

    // whatever operation with indices
    /* ... */

    // Now we change inplace the indices in order to get the next permutation
  } while(std::next_permutation(std::begin(indices), std::end(indices)));

  // The number of evaluations must be n! == 5! == 120
  assert(n_evaluations == 120);
}
```

Doing this with `HeapPermutationIterator` is a bit more complex, just because in C++ we are stepping the iteration **at the end** of the cycle, but this does not make sense with _range based_ iterators like in Rust.

What happens is that it is necessary to get the initial data before running the first iteration of `HeapPermutationIterator`, but it cannot be done without cloning because we also need to pass the mutable reference of the data in order to create the iterator.

Don't get me wrong, I understand that in this case the usability fights against basic design principles (why a permutation iterator **should not** permutate anything at its first iterator?). I am trying to explain the problem without trying to give a possible solution just because I don't have a good one in mind :disappointed:

**Comment by NattapongSiri** [comment]
I'd suggest to do something like this:
```Rust
extern crate permutator;
use permutator::Permutation;
// fill data with 0-4
let data : Vec<i32>= (0..5i32).map(|v| v).collect();
// process data before permute
some_data_user(&data);
// now permute it and process each permuted data
data.permutation().for_each(|permuted| {
    some_data_user(&permuted);
});
```

I didn't tried compile/run above code yet as I have no access to my Laptop for now.

**Comment by dodomorandi** [comment]
That works obviously, but in my case is a bit more complex and I combine the iterator with others operations and then I fold the result. Leaving the first iteration alone _breaks_ the functional approach and makes the approach a bit more error prone. In fact, in my real case I preferred to pay the cost of a clone to have a more maintainable code.

My question is if it is possible to get both maintainability and no initial cloning. One possible approach could be to have an iterable adapter that returns the original data on the first iteration and then starts the permutations, but it does not feel particularly elegant. What do you think?

**Comment by NattapongSiri** [comment]
Does unsafe code acceptable ?

**Comment by dodomorandi** [comment]
Do you mean for my specific case? I would rather not, and the cost of a clone is meaningless in terms of performance for my case.

My point is that it is common to use the initial data unchanged before the permutations, and trying to get this behaviour is not exactly straightforward. Maybe it could be nice to provide this kind of feature to the uses without breaking compatibility.

**Comment by NattapongSiri** [comment]
I’ll think about it. Thanks !

**Comment by dodomorandi** [comment]
If you want, I can provide a possible implementation. As I said, I am not sure about a _good solution_ in general, but maybe I can do something helpful :wink:

**Comment by NattapongSiri** [comment]
What I’m thinking is 

1. Add a kind of builder function that chain integrator where it first add unpermuted data.
2. Add a flag field that make iterator return unpermuted data as well.
3. Simply add function that turn this iterator to KPermutationIterator where k= length of data.
 In fact... 
Can you try using KPermutationIterator where k=data.len()please ?

**Comment by NattapongSiri** [comment]
Compare to HeapPermutationIterator, it won't be much different. In fact, it clone the entire ref to data. But all plain iterator always clone the ref anyway. The call back style counterpart is the one that doesn't clone anything at all.

**Comment by NattapongSiri** [comment]
Do you have any other issue using KPermutation ?
And does it cause any trouble in your use case ?

**Comment by dodomorandi** [comment]
I looked at the code some time ago, and I noticed that there is a good amount of work the handle the permutations. On the other hand, I never tried to perform some benchmark to understand the impact of the permutation respect to other things.

Maybe it could be worth to put an example in the documentation of `HeapPermutationIterator` to show that `KPermutationIterator` can be used to get the initial data with the first iteration.

**Comment by NattapongSiri** [comment]
Thanks for your comment !

**Comment by gralpli** [comment]
> 
> 
> I'd suggest to do something like this:
> 
> ```rust
> extern crate permutator;
> use permutator::Permutation;
> // fill data with 0-4
> let data : Vec<i32>= (0..5i32).map(|v| v).collect();
> // process data before permute
> some_data_user(&data);
> // now permute it and process each permuted data
> let mut n_evaluations = 1;
> data.permutation().for_each(|permuted| {
>     some_data_user(&permuted);
>     n_evaluations += 1;
> });
> 
> assert_eq!(n_evaluations, 120)
> ```

I’m not sure if this is a good choice for the API. I did’t expect this behavior as well. It also enforces code duplication. What if `.permutation()` consumed its collection and, in exchange, included the initial permutation?

**Comment by gralpli** [comment]
(I’m going to use `x_permutation` for now. Not because I need the lexicographical order, but because it includes _all_ the permutations.)

**Comment by NattapongSiri** [comment]
I just saw your comment. The reason behind this is because the performance concern.
See this line, https://github.com/NattapongSiri/permutator/blob/f5d9a250ef7e791daff1945098cbb9c0130a606d/src/lib.rs#L4133

In order to return the first result, either:
1. Every `next` call need to check if it's the first call.
1. Copy current value into another variable in HeapPermutationIterator then perform permutation then return the copied. This is due to Heap algorithm nature that permute array in place.

Both of them have performance penalty. That's why I decided to leave this to caller and redesign the callback version to behave to same way.

If you have suggestion on how to achieve it without performance penalty, I'd be happy to consider it.

**Comment by NattapongSiri** [comment]
@dodomorandi @gralpli 
Do you want to try this branch ?
https://github.com/NattapongSiri/permutator/tree/0.4.0

I change the way I implement trait `Permutation` so that it return `Chain` instead of HeapPermutation.
The `Chain` will also return original value. It'd have no impact to overall performance because the core algorithm remain the same.

**Comment by dodomorandi** [comment]
I just gave it a brief look, I will try to give a deeper look to the code on my spare time, hopefully. However, I noticed this:
https://github.com/NattapongSiri/permutator/blob/238c851027fe8f3a0b6b6c068b34ae68b370b214/src/lib.rs#L6149-L6152
You are allocating a `Vec` with one element, then you are transforming it into an iterator in order to chain the first non-permutated set of elements. Can you just use `std::iter::once` instead of allocating a `Vec`?

**Comment by NattapongSiri** [comment]
@dodomorandi Fixed according to the hint.

**Comment by NattapongSiri** [comment]
I'm closing it for now.
If you found any issue, please reopen it.
