### ISSUE TITLE
Calling combination with 23 objects and sample 2 results in panic

### ISSUE THREAD

**Issue by apanloco** [NattapongSiri/permutator#15]
This code triggers a panic:

```rust
use permutator::Combination;

#[test]
fn test_permutator() {
    let mut a = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23];
    for mut _c in a.combination(2) {
    }
}
```

error:
```
attempt to multiply with overflow
```

I'm wondering if there is any way around this? Thanks!

permutator version 0.4.0.

EDIT: removed embarrassing hypothesis

**Comment by NattapongSiri** [comment]
Sorry for long delay. I am very occupied with production deployment of my day job. I've fixed it now. Please use version 0.4.1

**Comment by NattapongSiri** [comment]
I just replicate all the short circuit calculation to every other length calculation in v0.4.2. So feel free to use this version as well.
