### ISSUE TITLE
SelfCartesianProductIterator panics when n>len

### ISSUE THREAD

**Issue by TheIronBorn** [NattapongSiri/permutator#16]
SelfCartesianProductIterator panics with an out of bounds error when `domain.len() < n`.

```rust
let data = [0, 1];
// expected
for x in CartesianProductIterator::new(&[&data[..]; 3][..]) {
    println!("{:?}", x);
}
// panics
for x in SelfCartesianProductIterator::new(&data, 3) {
    println!("{:?}", x);
}
```

`self_cartesian_product` seems to work fine.

---
permutator: `0.4.0`

**Comment by NattapongSiri** [comment]
Fixed in v0.4.3. Please update to this version and retry. Thanks for reporting !
